version: "3.1"
networks:
  shopline:
    driver: bridge
    external: true
services:
  shopline_server:
    build: ./
    container_name: shopline_server
    working_dir: /data/project
    tty: true
    volumes:
      - .:/data/project
    ports:
      - "9591:9501"
    command: php bin/hyperf.php start
    links:
      - rabbitmq
      - redis
    networks:
      shopline:
        ipv4_address: 179.41.0.8
  redis:
    image: redis:alpine
    container_name: shopline_server_redis
    ports:
     - "6690:6379"
    networks:
      shopline:
        ipv4_address: 179.41.0.4
  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    hostname: myrabbitmq
    restart: always
    volumes:
      - ./queue/rabbitmq:/var/lib/rabbitmq/mnesia
    ports:
      - "5672:5672" # mq
      - "15672:15672" # admin
      - "4369:4369"
      - "25672:25672"
    networks:
      shopline:
        ipv4_address: 179.41.0.9
